# config context path to "/" by setting an empty string

server:
  contextPath:
  port: 18086

# JACKSON
spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true
  application:
    name: auth_service

jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  route:
    authentication:
      path: auth
      refresh: refresh

eureka:
  client:
    service-url:
      defaultZone: http://localhost:18082/eureka/

#logging:
#  level:
#    org.springframework:
#      security: DEBUG